feat: listen events
ChainSafe/sygma-validator-faucet pull request #35
Opened 2023-03-21 15:16 UTC by irubido

Closes #20 

Issues:
```
        const events = goerliBridgeContract.events.ProposalExecution();
        events.on('data', (log) => {

        });
```
https://docs.web3js.org/docs/guides/web3_migration_guide/contracts_migration_guide/

this events.on never returned anything, so current solution uses getPastEvents in interval
```
goerliBridgeContract.getPastEvents(
            'ProposalExecution',
          )
```

possible workaround

axios.get(`${BEACONCHAIN_URL}/api/v1/validator/${pubkeys.join(',',)}/deposits`
and check status, example

https://goerli.beaconcha.in//api/v1/validator/90cafcd9b8508bdb183166d8b8456ea4f6d2cfd2207f0f1555e6a407d86bbb9f3d550ca7d2c0947f5e96fa111ea5ecfd/deposits

2023-03-22 08:36 UTC, BeroBurny requested changes
LGTM just small needle issues

2023-03-22 08:36 UTC, BeroBurny commented on src/routes/root/Summary.tsx
> +          console.warn(receipt);
You should remove `console.warn`

2023-03-22 08:36 UTC, BeroBurny commented on src/routes/root/Transactions.tsx
> +    (async () => {
aiding `void` in front will solve eslint issue

2023-03-22 08:36 UTC, BeroBurny commented on src/routes/root/Transactions.tsx
> +        // });
commented code :sweat:

2023-03-22 08:36 UTC, BeroBurny commented on src/utils/network.ts
> +  }
no need to use `break` after `return` as function will stop executing on `return`

2023-03-22 09:04 UTC, mpetrunic requested changes

2023-03-22 09:08 UTC, mpetrunic commented
@irubido Be more midful about naming of contracts.
BridgeContract - you need that if you wanna monitor if transaction reverted for some reason. I don't think we need that, as we verify all the data so tx should never revert
DepositTarget contract - You don't need this for anything
DepositContract - contract deployed by EF, you should listen for DepositEvent there

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Summary.tsx
> +        .on('receipt', (receipt: TransactionReceipt) => {
You should listen on the Deposit event of the bridge contract here otherwise replacing transaction will screw the flow^^

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +        const depositAdapterContract: Contract<typeof bridgeABI> =
wrong variable name, should be originBridgeContract

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +        const logs = await depositAdapterContract.getPastEvents('Deposit');
you should pass option to specify block range, but you probably don't need this if you are gonna listen to that event immediately after tx is submitted

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +            eventLog.transactionHash?.toLowerCase() === transactionHash?.toLowerCase()
You should filter DepositEvent with correct sender, depositData as submitted in tx

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +        // @ts-ignore
why do you need this?

2023-03-22 10:48 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +            'ProposalExecution',
you should specify block range in option

2023-03-24 08:59 UTC, mpetrunic commented on package.json
> +    "web3-eth-contract": "^4.0.1-rc.0",
remove^^

2023-03-24 08:59 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +              console.log(eventLog.returnValues.data);
console logs be gone!

2023-03-24 08:59 UTC, mpetrunic commented on src/routes/root/Transactions.tsx
> +              'ProposalExecution',
with should listen for FailedExecution event

2023-03-24 15:19 UTC, irubido commented on package.json
> +    "web3-eth-contract": "^4.0.1-rc.0",
"Eventlog" type is missing from web3

2023-03-24 15:50 UTC, mpetrunic approved these changes

2023-03-27 08:25 UTC, BeroBurny approved these changes

2023-03-27 08:25 UTC, merged